
name: health
on:
  schedule:
    - cron: "28 * * * *"
jobs:
  health:
    runs-on: ubuntu-latest
    steps:
      - name: Refresh health
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://gipnews.vercel.app/api/refresh?section=health'
          method: 'POST'
          customHeaders: '{"id": "_pxR945hMZJu303ldfIrWsOLns6Q"}'
          timeout: 10000
          retry: 1
          retryWait: 5000