
name: science
on:
  schedule:
    - cron: "42 * * * *"
jobs:
  science:
    runs-on: ubuntu-latest
    steps:
      - name: Refresh science
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://godinprints.org/api/gipnews/refresh?section=science,technology'
          method: 'POST'
          customHeaders: '{"id": "_pxR945hMZJu303ldfIrWsOLns6Q"}'
          timeout: 15000
          
