
name: world
on:
  schedule:
    - cron: "7 * * * *"
jobs:
  world:
    runs-on: ubuntu-latest
    steps:
      - name: Refresh world
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://godinprints.org/api/gipnews/refresh?section=world'
          method: 'POST'
          customHeaders: '{"id": "_pxR945hMZJu303ldfIrWsOLns6Q"}'
          timeout: 15000
          
