name: review mails
on:
  schedule:
    - cron: "30 16 * * 0"
jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: review mails
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://godinprints.org/bookReviews'
          method: 'POST'
          customHeaders: '{"pass": "08162008"}'
          timeout: 15000
          
